version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - app-network
  api:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - app-network

networks:
  app-network:
